version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: deliveryapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/deliveryapp
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DRIVER: org.postgresql.Driver
      JWT_SECRET: your-secret-key-here
      JWT_EXPIRATION: 86400000
    depends_on:
      - postgres

volumes:
  postgres_data: 